name: Python CI

# Trigger the workflow on any push to the main branch or pull repuest 
on:
    push: 
        branches:
            - main
    pull_request:
        branches:
            -main 

jobs:
    test:
        runs-on: ubuntu-latest

        steps: 
            # step 1: Check out the code from the repository 
            - name: Checkout code
              uses: actions/checkout@v2

            # step 2 : Set up a python environment 
            - name: Set up Python 
              uses: actions/setup-python@v2
              with: 
                python-version: '3.8'

            # step 3: Install the required packages
            - name: Install packages
              run: |
                pip -m pip install --upgrade pip
                pip install -r requirements.txt


            # step4: Run the test cases
            - name: Run tests
              run: pytest 


